version: 2
updates:
  - package-ecosystem: 'pip'
    directory: '/'
    schedule:
      interval: 'daily'
    allow:
      - dependency-type: 'direct'
    reviewers:
      - 'VKCOM/vk-sec'
      - 'VKCOM/vk-data'